config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources :jobs
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount SimpleDiscussion::Engine => "/forum"
  post 'intents', to: "jobs#intents"


  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  end

  get '/dashboard/:id', to: 'dashboard#dashboard', as: 'dashboard'


  root to: 'home#index'

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                  :bigint           not null, primary key
#  company_email       :string
#  company_name        :string
#  company_website     :string
#  compensation_range  :string
#  compensation_type   :string
#  estimated_hours     :string
#  featured            :boolean          default(FALSE)
#  featured_until      :datetime
#  headquarters        :string
#  link_to_apply       :string
#  price               :integer
#  published_at        :datetime
#  remote              :boolean          default(FALSE)
#  slug                :string
#  status              :string           default("pending")
#  title               :string
#  upsell_type         :string
#  years_of_experience :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :bigint           not null
#
# Indexes
#
#  index_jobs_on_slug     (slug) UNIQUE
#  index_jobs_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Job < ApplicationRecord
  extend FriendlyId
  friendly_id :slug_candidates, use: [:slugged, :finders]

  # relations
  belongs_to :user
  has_rich_text :description
  has_rich_text :company_description
  # has_one_attached :company_logo
  has_one_base64_attached :company_logo

  # scopes
  scope :desc, -> { order(created_at: :desc) }
  scope :pending, -> { where(status: JOB_STATUSES[:pending]) }
  scope :published, -> { where(status: JOB_STATUSES[:published]) }
  scope :archived, -> { where(status: JOB_STATUSES[:archived]) }

  BASE_JOB_PRICE = 199
  GOOD_JOB_PRICE = BASE_JOB_PRICE + 49
  BETTER_JOB_PRICE = BASE_JOB_PRICE + 69
  GREAT_JOB_PRICE = BASE_JOB_PRICE + 149

  # pricing
  PRICING = {
    base: BASE_JOB_PRICE,
    good: GOOD_JOB_PRICE,
    better: BETTER_JOB_PRICE,
    great: GREAT_JOB_PRICE
  }

  UPSELL_TYPES = {
    no_thanks: "no-thanks",
    good: "good",
    better: "better",
    great: "great"
  }

  # constants
  COMPENSATION_TYPES = [
    "Contract",
    "Full-time"
  ]

  COMPENSATION_RANGES = [
    "15,000 - 20,000",
    "20,000 - 30,000",
    "30,000 - 40,000",
    "40,000 - 50,000",
    "50,000 - 60,000",
    "60,000 - 70,000",
    "70,000 - 80,000",
    "80,000 - 90,000",
    "90,000 - 100,000",
    "100,000 - 110,000",
    "110,000 - 120,000",
    "120,000 - 130,000",
    "130,000 - 140,000",
    "140,000 - 150,000",
    "150,000 - 160,000",
    "160,000 - 170,000",
    "170,000 - 180,000",
    "180,000 - 190,000",
    "190,000 - 200,000",
    "greater than 200,000"
].freeze

  HOURLY_RANGES = [
    "less than 10",
    "10-30",
    "30-60",
    "60-90",
    "more than 100"
].freeze

  JOB_STATUSES = {
    pending: "pending",
    published: "published",
    archived: "archived"
  }.freeze

  YEARS_OF_EXPERIENCE_RANGE = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "more than 10"].freeze

  def slug_candidates
    [:title, [:title, "#{Job.where(
      title: title, company_name: company_name
    ).count + 1}"]]
  end
  

  def pending?
    self.status == Job::JOB_STATUSES[:pending]
  end

  def published?
    self.status == Job::JOB_STATUSES[:published]
  end

  def archived?
    self.status == Job::JOB_STATUSES[:archived]
  end

  def new_friendly_id?
    if !slug?
      title_changed?
    else
      false
    end
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show, :search]

  # GET /jobs or /jobs.json
  def index
      @jobs = Job.published.desc
    if params[:search].blank?
      @jobs
    else
      @search = params[:search].downcase
      @jobs = Job.published.desc.where('lower(title) LIKE :search', search: "%#{@search}%")
    end
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)
    if !params[:job][:company_logo].empty?
      @job.company_logo.attach(data: params[:job][:company_logo], filename: "1_#{Time.current.to_i}", )
    end
    @job.user = current_user
    
    if @job.save
      render json: { redirect_url: job_url(@job), notice: "Thanks for posting! Your job is now pending review." }
    else
      render json: @job.errors
    end

  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params_edit)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def intents
    intent_amount = case params[:upsell_type].parameterize
    when Job::UPSELL_TYPES[:no_thanks]
      Job::PRICING[:base]
    when Job::UPSELL_TYPES[:good]
      Job::PRICING[:good]
    when Job::UPSELL_TYPES[:better]
      Job::PRICING[:better]
    when Job::UPSELL_TYPES[:great]
      Job::PRICING[:great]
    else
      Job::PRICING[:base]
    end

    intent_amount = intent_amount * 100

    @intent = Stripe::PaymentIntent.create({
      amount: intent_amount,
      currency: "usd",
      payment_method_types: ["card"]
    })

    render json: @intent
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Only allow a list of trusted parameters through.

  
  def job_params
    params.require(:job).permit(
      :company_email,
      # :company_logo,
      :company_name, 
      :company_website, 
      :company_description, 
      :compensation_range,
      :compensation_type,  
      :description, 
      :estimated_hours, 
      # :featured_until, 
      :headquarters, 
      :link_to_apply, 
      :price, 
      :remote, 
      :title, 
      :upsell_type, 
      :years_of_experience)
  end

  def job_params_edit
    params.require(:job).permit(
      :company_email,
      :company_logo,
      :company_name, 
      :company_website, 
      :company_description, 
      :compensation_range,
      :compensation_type,  
      :description, 
      :estimated_hours, 
      # :featured_until, 
      :headquarters, 
      :link_to_apply, 
      :price, 
      :remote, 
      :title, 
      :upsell_type, 
      :years_of_experience)
  end


end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<div class="p-10 bg-white border rounded">

<%= form_with(model: job, local: true, multipart: true) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-wrap items-center justify-between input-group">
    <div>
      <%= form.label :company_logo, class: "label" %>
      <%= form.file_field :company_logo %>
    </div>
    <% if form.object.company_logo.attached? %>
      <%= image_tag form.object.company_logo, class: "w-24 h-auto" %>
    <% end %>
  </div>

  <div>
    <%= form.label :title, class: "label" %>
    <%= form.text_field :title, class: "input" %>
  </div>

  <div class="grid grid-cols-1 lg:gap-6 lg:grid-cols-2 input-group">
    <div class="lg:col-span-1">
      <%= form.label :link_to_apply, class: "label" %>
      <%= form.text_field :link_to_apply, class: "input" %>
    </div>
    <div class="lg:col-span-1">
      <%= form.label :headquarters, class: "label" %>
      <%= form.text_field :headquarters, class: "input" %>
    </div>
  </div>

  <div class="input-group">
    <%= form.label :description, class: "label" %>
    <%= form.rich_text_area :description, class: "input trixEditorStyle" %>
  </div>

  <div class="grid grid-cols-1 lg:gap-6 lg:grid-cols-2 input-group">
    <div class="lg:col-span-1">
      <%= form.label :company_name, class: "label" %>
      <%= form.text_field :company_name, class: "input" %>
    </div>
    <div class="lg:col-span-1">
      <%= form.label :company_website, class: "label" %>
      <%= form.text_field :company_website, class: "input" %>
    </div>
  </div>

  <div class="input-group">
    <%= form.label :company_description, class: "label" %>
    <%= form.rich_text_area :company_description, class: "input trixEditorStyle" %>
  </div>
  
  <div class="flex items-center justify-start input-group">
      <div class="lg:w-1/3 pr-4">
        <%= form.label :compensation_type, class: "label" %>
        <div class="relative">
          <%= select_arrow %>
          <%= form.select :compensation_type, options_for_select(Job::COMPENSATION_TYPES, :selected => form.object.compensation_type), {}, {:class => "select"} %>
        </div>
      </div>

      <div class="px-4">
        <%= form.label :compensation_range, class: "label" %>
        <%= form.text_field :compensation_range, class: "input" %>
      </div>

      <div class="pl-4">
        <%= form.label :estimated_hours, class: "label" %>
        <%= form.text_field :estimated_hours, class: "input" %>
      </div>
  </div>



  <div class="input-group input-checkbox">
    <%= form.check_box :remote %>
    <%= form.label :remote, class: "label" %>
  </div>

    <div class="input-group lg:w-1/3 pr-4">
      <%= form.label :years_of_experience, class: "label" %>
      <div class="relative">
        <%= select_arrow %>
        <%= form.select :years_of_experience, options_for_select(Job::YEARS_OF_EXPERIENCE_RANGE, :selected => form.object.years_of_experience), {}, {:class => "select"} %>
      </div>
    </div>

  <div class="actions">
    <%= form.submit class: "btn btn-indigo"%>
  </div>
<% end %>

</div>

app/views/jobs/_job.html.erb
<%# @jobs.each do |job| %>
<%# end %>

<div class="relative bg-white">
    <%= link_to job, class: "border rounded-lg py-6 px-6 mb-4 block transition ease-in-out duration-300 hover:shadow-lg" do %>

    <%# <div class="border rounded-lg py-6 px-6 mb-4 block transition ease-in-out duration-300 hover:shadow-lg"> %>
     <% if job.company_logo.attached? %>
        <%= image_tag job.company_logo.variant(resize_to_fit: [200, 200]), class: "w-16 h-16" %>
     <% end %>
        

        <div class="flex items-center">
            <p class="text-gray-700"><%= job.company_name %></p>
            <% if job.featured? %>
                <span class="ml-2 px-2 py-px text-xs tracking-wide text-white uppercase bg-indigo-600 rounded-lg">Featured</span>
             <% end %>
        </div>

        <h3 class="text-xl font-black"><%= job.title %></h3>

        <% if job.compensation_type.downcase == "contract" %>
            <%= job.estimated_hours %> hours
        <% else %>
            <p class="text-sm"><%= number_to_currency(job.compensation_range,:unit=>'PHP ') %></p>
            <p class="text-sm"><%= job.compensation_type %></p>
            <p class="text-sm"><%= pluralize(job.years_of_experience, 'year') %> of experience</p>
        <% end %>

        

        <p class="text-sm">
            <% if job.remote %>
                Remote, 
            <% end %>
            <%= job.headquarters %>
        </p>

    <%# </div> %>

    <% end %>

    <% if admin? %>
        <div class="absolute top-0 right-0 mt-4 mr-4">
            <%= link_to 'Edit', edit_job_path(job), class: "underline mr-1" %>
            <%= link_to 'Delete', job, method: :delete, data: { confirm: 'Are you sure?' }, class: "underline" %>
        </div>
    <% end %>

</div>

app/views/jobs/edit.html.erb
<div class="max-w-4xl mx-auto">
    <%= render 'form', job: @job %>
</div>

app/views/jobs/index.html.erb
<div class="bg-white p-10 border mt-5">
<%= form_tag(jobs_path, :method => "get") do %>
    <div class="sm:flex items-center bg-white rounded-lg overflow-hidden py-1 justify-between max-w-2xl mx-auto">
        <%= search_field_tag :search, params[:search] , placeholder: "Job Title or Keyword", class: "form-control text-base text-gray-400 flex-grow border border-gray-400 px-2 outline-none rounded py-3"%>
        <div class="ms:flex items-center px-2 rounded-lg space-x-4 mx-auto ">
        <%= button_tag "Search", :class => "bg-indigo-600 rounded-md font-bold text-white px-6 py-3 transition duration-300 ease-in-out hover:bg-purple-600 mr-6", :name => nil %>
        </div>
      </div>
  <% end %>
</div>

<div id="jobs-index" class="container px-0 mx-auto lg:px-48 mt-5">
  <%= render @jobs %>
</div>

app/views/jobs/new.html.erb
<div class="flex items-center justify-center pt-6 text-center">
    <%= link_to '<span class="text-indigo-600 ">joblite</span><span class="text-indigo-300">.com</span>'.html_safe, root_path, class:"link text-2xl tracking-tight font-black text-purple-600", title: "joblite.com" %>
</div>
<div data-controller="jobs">
    <div data-jobs-target="mount"></div>
</div>

app/views/jobs/show.html.erb
<div class="container mx-auto px-4 lg:px-24 lg:my-10">

  <% if @job.pending? %>
  <div class="w-full p-3 mb-6 text-white bg-blue-400 rounded">
    Pending review
  </div>
  <% end %>

  <div class="flex flex-wrap items-center justify-between border-b lg:border-0">
    <%= link_to root_path, class: "mb-4 inline-flex items-center justify-start" do %>
    <%= render_svg "icons/arrow_back_ios", styles: "stroke-current w-4 h-4 text-gray-600" %>
      <p class="text-sm text-gray-600">Back to all jobs </p>
    <% end %>
  </div>

  <div class="grid grid-cols-1 pt-6 lg:grid-cols-12">

    <div class="lg:col-span-8">
    
      <h1 class="lg:text-4xl leading-tight text-3xl font-black text-indigo-600 mb-4"><%= @job.title %></h1>

      <p class="pb-2 mb-2 leading-tight text-gray-700">
        <% if @job.compensation_type.downcase == "contract" %>
          <%= @job.estimated_hours %> hours
        <% else %>
          <%= number_to_currency(@job.compensation_range,:unit=>'PHP ') %>
          <%= @job.compensation_type %>
          <%= pluralize(@job.years_of_experience, 'year') %> of experience
        <% end %>
      </p>
      
      <div class="border-b pb-3 mb-3">
        <% if @job.company_logo.attached? %>
            <div class="float-left mr-2">
              <%= image_tag @job.company_logo.variant(resize_to_fit: [25, 25]), class: "flex-shrink-0" %>
            </div>
          <% end %>
          <div class="float-none">
            <%= link_to @job.company_name, @job.company_website, class: "text-base text-gray-600 hover:text-indigo-600" %>
          </div>
      </div>


      <h3 class="mb-2 text-xs font-bold tracking-wider text-gray-900 uppercase">About the role</h3>
      <div class="prose">
        <%= @job.description %>
      </div>

      <h3 class="mt-10 mb-2 text-xs font-bold tracking-wider text-gray-900 uppercase">About the company</h3>
      <div class="prose mb-6">
        <%= @job.company_description %>
      </div>
    
      <%= link_to "Apply for this role", @job.link_to_apply, class: "btn text-white bg-indigo-600 py-2 px-4 hover:bg-indigo-500 lg:mr-2 border border-indigo-500" %>

      <% if author_of(@job) || admin?%>
        <%= link_to 'Edit', edit_job_path(@job) %>
      <% end %>
      
    </div>

    <%# <div class="lg:col-span-4 text-center"> %>
      <%# <div class="p-4 sticky top-0 p-6 mt-6 text-gray-700 bg-white border border-black rounded-lg shadow-sm"> %>
        <%# if @job.company_logo.attached? %>
          <%# <div class="flex justify-center"> %>
            <%# <div class="w-16 h-16 my-3 text-center"> %>
             <%#= image_tag @job.company_logo.variant(resize_to_fit: [200, 200]), class: "flex-shrink-0" %>
            <%# </div> %>
          <%# </div> %>
        <%# end %>
        <%# <p> %>
        <%#= link_to @job.company_name, @job.company_website, class: "text-base text-gray-600 hover:text-indigo-600" %>
        <%# </p> %>
        <%# <p class="text-lg font-black text-gray-800 lg:px-4 leading-tight mb-2"> %>
        <%#= @job.title %>
        <%# </p> %>
        <%# <p class="pb-3 mb-3 leading-tight text-gray-700"> %>
            <%# if @job.compensation_type.downcase == "contract" %>
              <%#= @job.estimated_hours %> 
              <%# hours <br/> %>
            <%# else %>
              <%#= @job.compensation_type %>
              <%#= number_to_currency(@job.compensation_range,:unit=>'PHP ') %>
              <%#= pluralize(@job.years_of_experience, 'year') %> 
              <%# of experience %>
            <%# end %>
        <%# </p> %>
        <%#= link_to "Apply for this role", @job.link_to_apply, class: "btn text-white bg-indigo-600 py-2 px-4 hover:bg-indigo-500 lg:mr-2 border border-indigo-500" %>
      <%# </div> %>
    <%# </div> %>

  </div>
</div>