config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  
  resources :jobs
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount SimpleDiscussion::Engine => "/forum"
  post 'intents', to: "jobs#intents"


  Rails.application.routes.draw do
    devise_for :users, controllers: {
      registrations: 'users/registrations',
      sessions: 'users/sessions'
    }
  end

  get '/dashboard/:id', to: 'dashboard#dashboard', as: 'dashboard'


  root to: 'home#index'

end

app/views/shared/_flash_notice.html.erb
<% flash.each do |type, message| %>
  <% if type == "alert" %>
    <div class="bg-red-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
  <% if type == "notice" %>
    <div class="bg-green-500">
      <div class="container px-2 py-4 mx-auto font-sans font-medium text-center text-white"><%= message %></div>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <% if content_for?(:title) %>
      <%= yield :title %> |
    <% end %>
    Joblite | Job Search
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="stripe-public-key" content="<%= Rails.application.credentials.dig(:stripe, :public_key) %>">

  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;900&display=swap" rel="stylesheet"> 
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag  'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<header class="bg-white shadow-sm">
  <div class="container mx-auto">
    <nav class="flex flex-wrap items-center justify-between px-3 py-6 text-gray-700 lg:px-10">
        <%= render "shared/left_nav"%>
        <%= render "shared/right_nav"%>
    </nav>
  </div>
</header>

app/views/shared/_left_nav.html.erb
<div class="flex items-center mr-6 flex-no-shrink pt-4">
    <%= link_to '<span class="text-indigo-600 text-4xl">joblite</span><span class="text-indigo-300">.com</span>'.html_safe, root_path, class:"link text-2xl tracking-tight font-black text-purple-600", title: "joblite.com" %>
</div>

<div class="items-center block w-full text-center lg:flex-1 lg:flex lg:text-left">
   
</div>

app/views/shared/_right_nav.html.erb
 <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
 


    <% if user_signed_in? %>
        <%= link_to "Edit account", edit_user_registration_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
        <%= link_to "Log out", destroy_user_session_path, method: :delete, class:"block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link" %>
    <% else %>
        <%= link_to "Login / Register", new_user_session_path, class: "block mt-4 lg:inline-block lg:mt-0 lg:mr-4 mb-2 lg:mb-0 link py-4 px-10 border rounded-lg border-gray-400 hover:bg-indigo-600 hover:text-white hover:border-indigo-400" %>
    <% end %>

    <%= link_to "Employers / Post job", new_job_path, class: "btn text-white bg-indigo-600 py-4 px-10 hover:bg-purple-600 lg:mr-2 rounded-lg" %>
    
</div>

app/views/shared/_select_arrow.html.erb
<svg class="w-2 h-2 absolute top-0 right-0 m-4 pointer-events-none" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 412 232"><path d="M206 171.144L42.678 7.822c-9.763-9.763-25.592-9.763-35.355 0-9.763 9.764-9.763 25.592 0 35.355l181 181c4.88 4.882 11.279 7.323 17.677 7.323s12.796-2.441 17.678-7.322l181-181c9.763-9.764 9.763-25.592 0-35.355-9.763-9.763-25.592-9.763-35.355 0L206 171.144z" fill="#648299" fill-rule="nonzero"/></svg>

app/views/shared/_spacer.html.erb
<hr/>